title: 'Selección genómica en arroz: efecto del número de marcadores y de individuos genotipados sobre la precisión de la predicción'
description:
logo: logo/logo.gif
show_downloads: true
theme: jekyll-theme-minimal
plugins:
  - jemoji