project:
  type: book
  output-dir: docs

book:
  title: "Tutorial básico con SeqBreed"
  author: "Jorge Leonardo López Martínez<br>Miguel Pérez-Enciso"
  cover-image: images/logo.gif
  site-url: https://leo4luffy.github.io/Repo_TFM/
  repo-url: https://github.com/Leo4Luffy/Repo_TFM/tree/main/TFM_resultados
  repo-branch: master
  repo-actions: [edit]
  chapters:
    - index.qmd
    - data.qmd
    - model.qmd
    - seqbreed.qmd

format:
  html:
    highlight-style: a11y-dark
    theme: cosmo
    css: css/bloques.css
    cover-image: images/logo.gif
    code-link: true
