---
execute: 
  warning: false
  message: false
---

## SeqBreed {.unnumbered}

Hola

```{r}
#| label: paquetes
#| eval: true
#| echo: false

pacman::p_load(here, tidyverse, ggforce)
```

```{r}
#| label: fig-seqbreed
#| eval: true
#| echo: false
#| out-width: '74%'
#| fig-align: 'center'
#| fig-cap: 'Esquema de predicción usando simulación con el paquete SeqBreed.'

Puntos <- data.frame(x = c(8.2, 11.8, 13.4, 14.8, 11.4), y = c(8.2, 8.2, 3.35, -0.25, -6.6))

data.frame(
  x = 10.0, y = -7.8
  ) %>%
  ggplot(aes(x0 = x, y0 = y, r = 0.8)) +
  #geom_blank() +
  annotate(geom = 'rect', xmin = 7.8, xmax = 12.2, ymin = 4.3, ymax = 5.1, colour = 'yellow', fill = 'yellow', alpha = 0.2) +
  annotate(geom = 'text', x = 10.0, y = 4.7, label = 'Población fundadora', size = 4.0, colour = 'black') +
  #annotate(geom = 'text', x = 10.0, y = 4.5, label = '(G, y)', size = 4.4, colour = 'black') +
  
  annotate(geom = 'rect', xmin = 3.6, xmax = 8.0, ymin = 7.2, ymax = 8.0, colour = 'black', fill = 'black', alpha = 0.2) +
  annotate(geom = 'text', x = 5.8, y = 7.6, label = 'Genotipos fundadores', size = 4.0, colour = 'black') +
  geom_curve(x = 5.8, xend = 7.6, y = 6.9, yend = 5.35, arrow = arrow(length = unit(0.1, 'inch')), size = 0.5, color = 'black', curvature = 0.0) +
  
  annotate(geom = 'rect', xmin = 12.0, xmax = 16.4, ymin = 6.4, ymax = 8.0, colour = 'black', fill = 'black', alpha = 0.2) +
  annotate(geom = 'text', x = 14.2, y = 7.6, label = 'Localización de QTN', size = 4.0, colour = 'black') +
  annotate(geom = 'text', x = 14.2, y = 6.8, label = 'y efectos', size = 4.0, colour = 'black') +
  geom_curve(x = 14.2, xend = 12.4, y = 6.1, yend = 5.35, arrow = arrow(length = unit(0.1, 'inch')), size = 0.5, color = 'black', curvature = 0.0) +
  
  geom_curve(x = 10.0, xend = 10.0, y = 4.1, yend = 1.6, arrow = arrow(length = unit(0.1, 'inch')), size = 0.5, color = 'black', curvature = 0.0) +
  geom_curve(x = 10.8, xend = 10.2, y = 2.75, yend = 2.75, arrow = arrow(length = unit(0.1, 'inch')), size = 0.5, color = 'black', curvature = 0.0) +
  annotate(geom = 'rect', xmin = 11.0, xmax = 13.2, ymin = 2.35, ymax = 3.15, colour = 'black', fill = 'black', alpha = 0.2) +
  annotate(geom = 'text', x = 12.1, y = 2.75, label = 'Pedigrí', size = 4.0, colour = 'black') +
  
  annotate(geom = 'rect', xmin = 8.0, xmax = 12.0, ymin = 0.5, ymax = 1.3, colour = 'yellow', fill = 'yellow', alpha = 0.2) +
  annotate(geom = 'text', x = 10.0, y = 0.9, label = 'Población', size = 4.0, colour = 'black') +
  
  geom_curve(x = 10.0, xend = 10.0, y = 0.3, yend = -2.0, arrow = arrow(length = unit(0.1, 'inch')), size = 0.5, color = 'black', curvature = 0.0) +
  geom_curve(x = 10.8, xend = 10.2, y = -0.75, yend = -0.75, arrow = arrow(length = unit(0.1, 'inch')), size = 0.5, color = 'black', curvature = 0.0) +
  annotate(geom = 'rect', xmin = 11.0, xmax = 14.6, ymin = -1.25, ymax = -0.35, colour = 'black', fill = 'black', alpha = 0.2) +
  annotate(geom = 'text', x = 12.8, y = -0.75, label = 'Densidad de SNP', size = 4.0, colour = 'black') +
  
  annotate(geom = 'rect', xmin = 9.6, xmax = 10.8, ymin = -4.0, ymax = -2.2, colour = 'black', fill = 'white') +
  annotate(geom = 'rect', xmin = 10.1, xmax = 10.7, ymin = -3.75, ymax = -2.9, colour = 'cyan', fill = 'cyan', alpha = 0.2) +
  annotate(geom = 'text', x = 9.2, y = -3.1, label = 'Matriz H', size = 4.6, angle = 90, colour = 'black') +
  
  geom_curve(x = 10.0, xend = 10.0, y = -4.2, yend = -6.3, arrow = arrow(length = unit(0.1, 'inch')), size = 0.5, color = 'black', curvature = 0.0) +
  annotate(geom = 'rect', xmin = 9.5, xmax = 10.5, ymin = -7.5, ymax = -6.5, colour = 'black', fill = 'black', alpha = 0.4) +
  annotate(geom = 'rect', xmin = 9.95, xmax = 10.05, ymin = -7.8, ymax = -7.5, colour = 'black', fill = 'black', alpha = 0.7) +
  geom_circle(aes(x0 = x, y0 = y, r = 0.2), colour = 'black', fill = 'black', alpha = 0.7, size = 0.7) +
  annotate(geom = 'rect', xmin = 10.7, xmax = 11.1, ymin = -7.8, ymax = -6.5, colour = 'black', fill = 'black', alpha = 0.2) +
  annotate(geom = 'rect', xmin = 10.85, xmax = 10.95, ymin = -7.5, ymax = -7.3, colour = 'black', fill = 'black', alpha = 0.5) +
  annotate(geom = 'rect', xmin = 10.88, xmax = 10.92, ymin = -6.8, ymax = -6.9, colour = 'black', fill = 'black', alpha = 0.5) +
  annotate(geom = 'text', x = 9.1, y = -7.0, label = 'ssGBLUP', size = 4.6, angle = 90, colour = 'black') +
  annotate(geom = 'text', x = 8.7, y = -7.0, label = 'BLUP', size = 4.6, angle = 90, colour = 'black') +
  
  annotate(geom = 'text', x = 8.2, y = 8.2, label = '1', family = 'gochi', size = 5.8, colour = 'black') +
  annotate(geom = 'text', x = 11.8, y = 8.2, label = '2', family = 'gochi', size = 5.8, colour = 'black') +
  annotate(geom = 'text', x = 13.4, y = 3.35, label = '3', family = 'gochi', size = 5.8, colour = 'black') +
  annotate(geom = 'text', x = 14.8, y = -0.25, label = '4', family = 'gochi', size = 5.8, colour = 'black') +
  annotate(geom = 'text', x = 11.4, y = -6.6, label = '5', family = 'gochi', size = 5.8, colour = 'black') +
  geom_point(aes(x = x, y = y), data = Puntos, size = 6, shape = 1, color = 'black') +
  
  scale_x_continuous(limits = c(2.5, 17.5)) +
  scale_y_continuous(limits = c(-8.3, 8.5)) +
  
  theme_bw() +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank())
```
